format = "\\[$username@$hostname\\] $all"

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[directory]
truncation_length = 100
truncate_to_repo = false

[username]
format = '[$user]($style)'
show_always = true

[hostname]
format = '[$ssh_symbol$hostname]($style)'
ssh_only = false

[package]
disabled = true

[gcloud]
disabled = true

[aws]
disabled = true

[openstack]
disabled = true